### ISSUE TITLE
New cop to narrow down `assert_raises` bodies

### ISSUE THREAD

**Issue by fatkodima** [rubocop/rubocop-minitest#109]
```ruby
# bad
assert_raises(...) do
  some_other_code
  do_something
end

# good
some_other_code

assert_raises(...) do
  do_something
end
```

It is a good practice to make `assert_raises` bodies as small as possible, so that:
1) it is obvious which method call is tested for error 
2) and when multiple calls inside `assert_raises` can raise the same kind of an exception, there won't be false positives and the right method is tested

So this cop will suggest that `assert_raises` body contains only 1 top level node and it should of `send/csend` type.

@koic Wdyt on this?

**Comment by koic** [comment]
This looks good to me. I think this cop can accept blocks (`block` type) as follows.

```ruby
# good
assert_raises(...) do
  do_something do
    foo
    bar
  end
end
```
