### ISSUE TITLE
Could we make `MultipleAssertions` support minimums too?

### ISSUE THREAD

**Issue by ghiculescu** [rubocop/rubocop-minitest#123]
Looking for feedback on adding a `min` option to https://github.com/rubocop/rubocop-minitest/blob/master/lib/rubocop/cop/minitest/multiple_assertions.rb

Ideally it could catch things like this:

```ruby
def test_forgot_to_write_assertions
  # do things but never assert anything
end
```

Currently the test will pass unless it raises. But that's potentially a bug or oversight in the test.

Use case: sometimes when writing tests I'll write a bunch of the form:

```ruby
def test_a
  flunk
end

def test_b
  flunk
end

def test_c
  flunk
end
```

And then fill them in as I go. It would be nice to not have to remember to `flunk` and just have the linter remind you of this.

I'm happy to build this, if it would be accepted.

**Comment by andyw8** [comment]
Although it's similar, I think this should be a separate cop from `MultipleAssertions`. The existing code encourages _better_ tests, but the rule you're suggesting here is for detecting an _invalid_ test. Also, setting `Min: 1` would make sense, but I can't imagine any situation where there would be a need to set `Min` to 2 or any other value.

Another thing to keep in mind is that assertion may happen in a method called by the test, in which case it wouldn't be possible to catch through static analysis.

I'm also wondering if this is something that could be better implemented in minitest itself, or as a plugin...

**Comment by andyw8** [comment]
Here's another approach to catching tests without assertions:

https://railsatscale.com/2024-01-25-catching-assertionless-tests
