### ISSUE TITLE
Minitest/AssertWithExpectedArgument flags a common assertion in model tests.

### ISSUE THREAD

**Issue by ccasabona** [rubocop/rubocop-minitest#126]
The new Minitest/AssertWithExpectedArgument cop flags a valid assertion used in Rails model tests.

With a User class that has a required name attribute, a test for this may be written as:

```
    test 'name exists' do
      @user.name = ''
      assert @user.invalid?, @user.errors[:name]
      assert_equal [I18n.t('errors.messages.blank')], @user.errors[:name]
      @user.name = 'charlie'
      assert @user.valid?, @user.errors.full_messages
    end

```
The last assertion, assert @user.valid?, @user.errors.full_messages, is (or used to be) an acceptable way of returning an unexpected error message for an assert something.valid? statement that you expect to be true.  Should the @user instance not be valid, any errors are displayed.

Obviously, once the unexpected condition is corrected, the @user.error.full_messages part of the statement is no longer needed.  Our model tests, however, have about 1300 lines that use this structure.

**Comment by koic** [comment]
RuboCop Minitest 0.11.1 has been released with unsafe mark to the cop. In the future, if there are many similar issues, I think this cop can consider disabling it by default. Thank you for your feedback.

**Comment by ccasabona** [comment]
Thank you for looking into this.
