### ISSUE TITLE
Minitest/GlobalExpectations doesn't seem to be triggered

### ISSUE THREAD

**Issue by baxter** [rubocop/rubocop-minitest#134]
I'm sure I must have configured something incorrectly, but I can't figure out what.

I created a new project, installed the rubocop and rubocop-minitest gems, then added the following .rubocop.yml:

```yaml
require:
  - rubocop-performance
  - rubocop-minitest
```

I then added the following spec

```ruby
# frozen_string_literal: true

require 'minitest/autorun'
require_relative './meme'

describe Meme do
  before do
    @meme = Meme.new
  end

  describe 'when asked about cheeseburgers' do
    it 'must respond positively' do
      @meme.i_can_has_cheezburger?.must_equal 'OHAI!'
    end
  end

  describe 'when asked about blending possibilities' do
    it "won't say no" do
      @meme.will_it_blend?.wont_match(/^no/i)
    end
  end
end
```

And ran the following command:

```bash
rubocop --auto-correct --only Minitest/GlobalExpectations example_spec.rb
```

And got the following output:

```
Inspecting 1 file
.

1 file inspected, no offenses detected
```

My versions of rubocop and rubocop-minitest are:

```
rubocop (1.16.1)
rubocop-ast (1.7.0)
rubocop-minitest (0.12.1)
rubocop-performance (1.11.3)
```

My expectation is that this would have resulted in 2 offenses detected. Can anyone confirm whether this is a bug or I'm doing something dumb?

Thank you!

**Comment by koic** [comment]
By default, `test` directory, or file name ends with `_test.rb` are targeted for detection. `_spec.rb` is not the target. 
https://github.com/rubocop/rubocop-minitest/blob/v0.12.1/config/default.yml#L3-L5

Thank you.

**Comment by andyw8** [comment]
I'm not sure if it's a strong convention, but here's an example of name with`_spec.rb`:

https://semaphoreci.com/community/tutorials/getting-started-with-minitest

If further examples can be found, then perhaps the behaviour could be changed.

**Comment by baxter** [comment]
Oh I didn't realise, thank you!

I added this to my .rubocop.yml and this fixed the issue.

```yaml
Minitest:
  Include:
    - '**/spec/**/*'
    - '**/*_spec.rb'
```

**Comment by koic** [comment]
After that, I investigated about this issue. As a result, it could include `'**/test/**/*_spec.rb'` compliant Minitest::Spec. However, it doesn't include `'**/spec/**/*_spec.rb'` for the following reasons:

- Not officially present in Minitest
- Preventing false positives in RuboCop RSpec

I opened #135. Thank you.
