### ISSUE TITLE
Cop suggestion: Encourage test phase separation (Four-Phase Test or Arrange Act Assert)

### ISSUE THREAD

**Issue by andyw8** [rubocop/rubocop-minitest#139]
A common approach when writing tests is the [four-phase test](https://thoughtbot.com/blog/four-phase-test), sometimes referred to as [Arrange Act Assert](https://www.justinweiss.com/articles/writing-better-tests-with-the-three-phase-pattern/).

Parsing the code to determine if the test was correctly split up probably wouldn't be feasible, but we could ensure that each test had at least one line of whitespace.

cc @jakxz

**Comment by koic** [comment]
It can be understand as a coding advice. I saw this style in JUnit about 15 years ago. However, it is difficult to determine whether a blank line means a separation of those semantics by the static analysis. I'll close this issue, but thank you for your suggestion.
