### ISSUE TITLE
Cop Feature Request: Catch assert expression.nil? and suggest assert_nil instead

### ISSUE THREAD

**Issue by Ryan1729** [rubocop/rubocop-minitest#140]
## Is your feature request related to a problem? Please describe.

The `AssertNil` and `RefuteNil` cops do catch cases like the following, and suggests `assert_nil` instead:

```ruby
assert_equal nil, expression
```

But they don't catch cases that use `.nil?` like this:
```ruby
assert expression.nil?
```

[The minitest style guide currently even uses a `.nil?` example for Refute Nil](https://minitest.rubystyle.guide/#refute-nil).

## Describe the solution you'd like

It would be nice if the `AssertNil` and `RefuteNil` cops could catch these `.nil?` cases too.

## Describe alternatives you've considered

It's not hard to write a regex for this myself, but having this be part of rubocop-minitest would be more convenient.

## Additional context

N/A

**Comment by abhaynikam** [comment]
IMO, it is not a bad practice to use `assert expression.nil?` or `refute expression.nil?. I think the documentation should be updated. 

The cop was introduced because `assert_nil` and `refute_nil` is deprecated in minitest. 😊

**Comment by andyw8** [comment]
Do you know when it was deprecated? I can't see a mention in https://github.com/seattlerb/minitest/blob/master/History.rdoc

**Comment by abhaynikam** [comment]
> The cop was introduced because assert_nil and refute_nil is deprecated in minitest.

Sorry. My bad. I meant `assert_equal nil, expression` was deprecated. Here is the deprecation warning: https://github.com/seattlerb/minitest/blob/master/lib/minitest/assertions.rb#L227 😊

**Comment by Ryan1729** [comment]
I think a good reason to prefer `assert_nil expression` over `assert expression.nil?` is because with `assert_nil` you get more informative error messages.

For example, this assert:
```ruby
assert 1.nil?
```
results in this error message:
```
Minitest::Assertion: Expected false to be truthy.
```
But if you use `assert_nil` instead like this:
```ruby
assert_nil 1
```
you get this more informative error message:
```
Minitest::Assertion: Expected 1 to be nil.
```

Yes, you can go look at the test to figure out what happened, but it's slightly nicer to see the expression that caused the issue right in the error message.
