### ISSUE TITLE
Minitest/GlobalExpectations: configure extra matcher methods

### ISSUE THREAD

**Issue by gi** [rubocop/rubocop-minitest#152]
## Is your feature request related to a problem? Please describe.

In one of my projects, there are other matcher methods that are not a part of the core Minitest library (perhaps an extension) but which would be nice to include in this cop.

## Describe the solution you'd like

Add a configuration field which includes additional matcher methods for which to check:
```markdown
AdditionalMethods:
  - must_match_array
  - wont_match_array
```

## Describe alternatives you've considered

A custom cop is not maintainable.

## Additional context

No.

**Comment by koic** [comment]
> In one of my projects, there are other matcher methods that are not a part of the core Minitest library (perhaps an extension)

@gi I have a question. Are these (`must_match_array` and  `wont_match_array`) open source 3rd party custom matchers? Or is it your project's own proprietary custom matchers?

**Comment by koic** [comment]
I'm going close this issue because no response for a long time.
