### ISSUE TITLE
Support `ActiveSupport::TestCase`

### ISSUE THREAD

**Issue by andyw8** [rubocop/rubocop-minitest#166]
## Is your feature request related to a problem? Please describe.

`ActiveSuppport::TestCase` inherits from `Minitest::Test` but isn't recognized by the `test_class?` method since it doesn't end in `Test`:

https://github.com/rubocop/rubocop-minitest/blob/50ce80a009fbf8bb1c627176b19c0100b865d2fa/lib/rubocop/cop/mixin/minitest_exploration_helpers.rb#L24-L26

## Describe the solution you'd like

Match on `TestCase` as well as `Test`.

## Describe alternatives you've considered

n/a

## Additional context

n/a

**Comment by koic** [comment]
Can you provide a real world example? e.g. something from the rails/rails repository.

**Comment by andyw8** [comment]
I think almost every test in `rails/rails` inherits from that, e.g.

https://github.com/rails/rails/blob/main/activesupport/test/benchmarkable_test.rb

**Comment by koic** [comment]
@andyw8 I think RuboCop Minitest already has the expected behavior, what do you think?

**Comment by andyw8** [comment]
Ah, it seems it does. I mis-read it as checking the test class name rather than the parent class name.

I don't remember the context of where I ran into a problem with this, so I'll close it for now.
