### ISSUE TITLE
`refute_predicate` triggers suggestion for `assert_not_predicate` but this method does not exist in Minitest.

### ISSUE THREAD

**Issue by davidwessman** [rubocop/rubocop-minitest#182]
## Expected behavior
```ruby
refute_predicate(company, :active?)
```

Rubocop should  not warn, because `assert_not_predicate` does not exist.

## Actual behavior

```ruby
refute_predicate(company, :active?)
```

Output
```sh
C: [Correctable] Rails/RefuteMethods: Prefer assert_not_predicate over refute_predicate.
          refute_predicate(company, :active?)
``` 

## Steps to reproduce the problem
1. Create a file with `refute_predicate(company, :active?)`
2. `rubocop ./file_with_refute_predicate.rb`

## RuboCop version

```
$ bundle exec rubocop -V
1.35.1 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 2.7.6 x86_64-darwin21)
  - rubocop-minitest 0.22.0
  - rubocop-performance 1.14.3
  - rubocop-rails 2.16.0
```

## Minitest version
minitest (5.16.3)

**Comment by davidwessman** [comment]
I am also using standard 1.16.1, if that might cause problems.

**Comment by koic** [comment]
`assert_not_predicate` is defined in `ActiveSupport::TestCase` of Rails.

- `ActiveSupport::TestCase#assert_not_predicate` ... https://github.com/rails/rails/blob/v7.0.4/activesupport/lib/active_support/test_case.rb#L145

So the warning is triggered by `Rails/AssertNot` cop of rubocop-rails, not a rubocop-minitest issue.

- `Rails/AssertNot` cop ... https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsassertnot

If you don't use Rails (i.e. pure Ruby) , please remove rubocop-rails from .rubocop.yml and Gemfile.

**Comment by davidwessman** [comment]
I have no idea what I did to get errors yesterday, but now it all works as it should...

Thank you for a very thorough answer, this was totally on me :/
