### ISSUE TITLE
Edge cases in `Minitest/EmptyLineBeforeAssertionMethods`

### ISSUE THREAD

**Issue by flavorjones** [rubocop/rubocop-minitest#189]
The `Minitest/EmptyLineBeforeAssertionMethods` cop has some behaviors related to blocks (like `#each` loops) that I think either result in unnecessary warnings or missed warnings.

## Example

```ruby
require "minitest/autorun"
require "set"

class FooTest < MiniTest::Spec
  def test_foo
    set = Set.new([1,2,3])
    refute_nil(set)
    set.each do |thing|
      refute_nil(thing)
    end
    assert_equal(6, set.inject(:+))
  end

  def test_bar
    set = Set.new([1,2,3])
    set.each do |thing|
      refute_nil(thing)
    end
  end
end
```

## Actual behavior

```
test/test_foo.rb:7:5: C: [Correctable] Minitest/EmptyLineBeforeAssertionMethods: Add empty line before assertion.
    refute_nil(set)
    ^^^^^^^^^^^^^^^
test/test_foo.rb:11:5: C: [Correctable] Minitest/EmptyLineBeforeAssertionMethods: Add empty line before assertion.
    assert_equal(6, set.inject(:+))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Expected behavior

In `test_foo`, I do expect the warning on line 7, but I do not expect the warning on line 11.

In `test_bar`, I would expect a warning to appear before the `set.each` line.

In situations like this, I expect that a block containing only assertions should be treated as if it was an assertion.

## RuboCop version

```
1.37.1 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 3.1.2) [x86_64-linux]
  - rubocop-minitest 0.23.0
```

**Comment by movermeyer** [comment]
Similarly, in this case:

```ruby
test "i18n load path yaml files are formatted properly" do
  yaml_load_paths.each do |path|
    YAML.load_file(path)
  rescue Psych::Exception => e
    flunk("Error loading #{path}: #{e.inspect}")
  end
end
```

I would not expect `Minitest/EmptyLineBeforeAssertionMethods` to find an offense.

**Comment by MatzFan** [comment]
With rubocop-minitest 0.31.1 I'm still getting a false positive for Minitest/EmptyLineBeforeAssertionMethods on this code for the `refute_nil(thing)` within the block.

```ruby
require "minitest/autorun"
require "set"

class FooTest < MiniTest::Spec
  def test_bar
    set = Set.new([1,2,3])
    set.each do |thing|
      refute_nil(thing)
    end
  end
end
```

**Comment by koic** [comment]
@MatzFan It looks like it's an expected behavior and doesn't have a false positive:
https://github.com/rubocop/rubocop-minitest/blob/v0.31.1/test/rubocop/cop/minitest/empty_line_before_assertion_methods_test.rb#L130-L150

If you have different intentions regarding the above test, please open a new issue based on the template. Thank you.

**Comment by MatzFan** [comment]
Apologies, my mistake in not realizing I need to put a space before the block containing an assertion. Sorry for the false negative!
