### ISSUE TITLE
New cop to ensure 'skip' has a message

### ISSUE THREAD

**Issue by fatkodima** [rubocop/rubocop-minitest#198]
Inspired by - https://hexdocs.pm/credo/Credo.Check.Design.SkipTestWithoutComment.html.

It is possible to `skip` a test without providing a reason why - https://github.com/minitest/minitest/blob/ed224bc9983eab31cbb4859f655daeec903da046/lib/minitest/assertions.rb#L783

Future you or other developers will have a hard time figuring out why it was skipped. So I suggest to enforce `skip` messages. Unless it is in condition already.

Example
```ruby
# bad
skip

# good
skip("Is not supported by Active Record < 7")

# also good
skip if active_record_below_7?
```

**Comment by andyw8** [comment]
Seems like a useful cop 👍
