### ISSUE TITLE
Minitest/NoAssertions does not work with minitest/spec syntax

### ISSUE THREAD

**Issue by Narnach** [rubocop/rubocop-minitest#200]
Hi,

For a project I recently joined I noticed there was a test without assert.

I added `rubocop-minitest` and enabled `Minitest/NoAssertions` to help detect this.

To my surprise `Minitest/NoAssertions` did _not_ detect the test as having no assertions!

The root cause is that we use `minitest/spec` syntax rather than the class style. As a result we fail two internal preconditions of the current method used by NoAssertions to check if a method is a test and thus should be counted:

- have a class name ending in "Test" (a top-level describe block does something different)
- have a test name starting with "test_" (we use the `it "does something" do .. end` style instead of `test "something" do .. end` style)

I've created a failing test case similar to the ones that already exist in `test/rubocop/cop/minitest/no_assertions_test.rb` that describes the pattern of our test code. I'm unfamiliar with both Minitest and Rubocop internals so a fix appears to be harder to create.

Is this something that you would like to see resolved?

```ruby
  def test_registers_offense_when_no_assertions_in_spec_form
    assert_offense(<<~RUBY)
      describe Foo do
        setup { }
        teardown { }

        it "asserts the truth" do
          assert true
        end

        it "does nothing" do
        ^^^^^^^^^^^^^^^^^^^^ Test case has no assertions.
        end

        describe "when seen from the other side" do
          it "refutes falsehood" do
            refute false
          end
        end
      end
    RUBY
  end
```

**Comment by andyw8** [comment]
It's not explicitly stated anywhere, but as far I can tell there's never been any attempt to support `minitest/spec`. Some cops may 'just work', but I suspect there are some more don't, or wouldn't make sense for `minitest/spec`.

**Comment by koic** [comment]
For example, `Minitest/GlobalExpectations` is already supported, so `it` testing block can also be supported by RuboCop Minitest. I've opened #203.

**Comment by Narnach** [comment]
Thanks!
