### ISSUE TITLE
Loop between  Minitest/AssertTruthy and  Minitest/AssertWithExpectedArgument when passing `msg` option to `assert`

### ISSUE THREAD

**Issue by hjeebus** [rubocop/rubocop-minitest#206]
## desc
I think there is an issue when passing the optional argument `msg` that is allowed for all `assert*` methods. When using that optional argument **i think** the gem gets confused and thinks you want to test equality between the first argument (the test) and the second optional argument (msg). i've added more context to the expected behavior section with code examples.

ref: https://docs.ruby-lang.org/en/2.1.0/MiniTest/Assertions.html

--------

## Expected behavior
I expect `Minitest/AssertWithExpectedArgument` not to be raised when passing optional msg argument to `assert`

## Actual behavior
When passing `msg` rubocop complains about using `assert_equal(test, msg)`

## Steps to reproduce the problem
given:
```
  def assert_routes_get(path, msg = nil)
    msg = message(msg) { "Expected GET #{path} to be routable" }

    assert(routable?(method: :get, path:), msg)
  end
```
when:
`$ rubocop`

then:
```
C: Minitest/AssertWithExpectedArgument: Did you mean to use assert_equal(routable?(method: :get, path:), msg)?
    assert(routable?(method: :get, path:), msg)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
given:
```
  def assert_routes_get(path, msg = nil)
    msg = message(msg) { "Expected GET #{path} to be routable" }

    assert_equal(true, routable?(method: :get, path:), msg)
  end
```
when:
`$ rubocop -a`

then:
```
C: [Corrected] Minitest/AssertTruthy: Prefer using assert(routable?(method: :get, path:), msg).
    assert_equal(true, routable?(method: :get, path:), msg)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
and we are back to the first example...

## RuboCop version

```
$ bundle exec rubocop -V
1.41.1 (using Parser 3.1.3.0, rubocop-ast 1.24.0, running on ruby 3.1.2) [arm64-darwin21]
  - rubocop-minitest 0.25.0
  - rubocop-performance 1.15.1
  - rubocop-rails 2.17.3
```

**Comment by fatkodima** [comment]
https://github.com/rubocop/rubocop-minitest/blob/b97ae78e0f0f9f3d71131eae1bc18b3e7b3a6913/lib/rubocop/cop/minitest/assert_with_expected_argument.rb#L9-L11

So I think, the best solution is to just disable this cop for that line.

**Comment by koic** [comment]
I've opened #206. The second argument to the `assert` method named `message` and `msg` is allowed. Because their names are inferred as message arguments.
