### ISSUE TITLE
`Minitest/AssertTruthy` should be marked as unsafe for autocorrection

### ISSUE THREAD

**Issue by andyw8** [rubocop/rubocop-minitest#209]
If the intention is to check for a `true`/`false` value rather than truthy or falsey, then the autocorrection could result in a test passing when it shouldn't.

## Expected behavior

`assert_equal true, item.flagged` should not be autocorrected.

## Actual behavior

It is auto-corrected to `assert item.flagged`. So the test would still pass even if `flagged` returned a string.

## RuboCop version

rubocop-minitest (0.25.1)

**Comment by jana4u** [comment]
I think `Minitest/RefuteFalse` should be handled the same (marked as unsafe) to distinguish between `nil` and `false` then?

**Comment by koic** [comment]
@jana4u Good catch! I've opened https://github.com/rubocop/rubocop-minitest/pull/233.
