### ISSUE TITLE
`EmptyLineBeforeAssertionMethods` adds an empty line after an assertion with a block and before an assertion

### ISSUE THREAD

**Issue by adamzapasnik** [rubocop/rubocop-minitest#210]
`EmptyLineBeforeAssertionMethods` adds an empty line after an assertion with a block and before an assertion👇 

--------

## Expected behavior

```ruby
assert true
assert_raise ActiveRecord::RecordNotFound do
  something
end
assert true
assert_raise ActiveRecord::RecordNotFound do
  something

  assert true
end
assert true
```

## Actual behavior

```ruby
assert true
assert_raise ActiveRecord::RecordNotFound do
  something
end

assert true
assert_raise ActiveRecord::RecordNotFound do
  something

  assert true
end
assert true
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:
You see extension cop versions (e.g. rubocop-minitest, rubocop-performance, and others) output by rubocop -V,
include them as well. Here's an example:

```
1.41.1 (using Parser 3.1.3.0, rubocop-ast 1.24.0, running on ruby 3.0.5) +server [arm64-darwin22]
  - rubocop-minitest 0.25.1
  - rubocop-rails 2.17.4
  - rubocop-thread_safety 0.4.4
```

**Comment by adamzapasnik** [comment]
thx @koic

**Comment by koic** [comment]
@adamzapasnik You are welcome!
