### ISSUE TITLE
New cop: `Minitest/TestFileName`

### ISSUE THREAD

**Issue by fatkodima** [rubocop/rubocop-minitest#213]
This cop should check if we have a test class inside the file without the `_test` suffix. 
In this case, this file will be just ignored when running all the tests and go unnoticed.

**Comment by koic** [comment]
Can you point out bad and good cases with code?

**Comment by fatkodima** [comment]
Bad
```ruby
# Defined in test/something.rb file
class SomethingTest < Minitest::Test
  def test_foo
    # ...
  end
end
```

Good
```ruby
# Defined in test/something_test.rb file
class SomethingTest < Minitest::Test
  def test_foo
    # ...
  end
end
```

**Comment by tejasbubane** [comment]
I guess this cop will be very similar to [RSpec/FilePath](https://github.com/rubocop/rubocop-rspec/blob/c557186cd423cbf87feadf10daf4d029e2faf149/lib/rubocop/cop/rspec/file_path.rb).

**Comment by fatkodima** [comment]
Yes. Rspec's cop enforces that the file is named as a tested class also (besides the suffix). In minitest, sometimes in a single test file there are multiple test classes (a `rails/rails` is a good example). So I would not enforce that, or maybe under some flag.

**Comment by andyw8** [comment]
I added a guideline relating to this to the styleguide a while ago:

https://github.com/rubocop/minitest-style-guide#file-naming

And I just opened this PR:
https://github.com/rubocop/minitest-style-guide/pull/52

**Comment by andyw8** [comment]
(Brief reply as I'm on mobile). The naming convention could be configurable, to avoid the risk of the file name not matching an expected pattern, e.g. *_test
