### ISSUE TITLE
New cop: `Minitest/HooksGrouping`

### ISSUE THREAD

**Issue by fatkodima** [rubocop/rubocop-minitest#214]
Or there is a better name for this cop. 
It will check that `setup`/`teardown` are *before* all the test cases, and that `setup` is before `teardown`. It adds consistency and enforces the expectation of these methods to go first (to be easily noticeable/etc).

```ruby
# bad
class SomethingTest < Minitest::Test
  def setup; end
  def test_something; end
  def teardown; end
end

# bad
class SomethingTest < Minitest::Test
  def teardown; end
  def setup; end
  def test_something; end
end

# good
class SomethingTest < Minitest::Test
  def setup; end
  def teardown; end
  def test_something; end
end
```

**Comment by koic** [comment]
Yeah, the naming is difficult too, there is a better name 😅 Anyway, I think it's worth opening up to the style guide first:
https://github.com/rubocop/minitest-style-guide

**Comment by tejasbubane** [comment]
Better name would be `Minitest/HooksOrder` similar to `Style/RequireOrder`, `Style/KeywordParametersOrder`, `Rails/ActiveRecordCallbacksOrder`, etc.

Additionally I tink it should check for all hooks including the `before` and `after` methods:

```ruby
# bad
class SomethingTest < Minitest::Test
  def after_teardown; end
  def before_teardown; end
  def setup; end
  def before_setup; end
  def after_setup; end
  def teardown; end
end

# good
class SomethingTest < Minitest::Test
  def before_setup; end
  def setup; end
  def after_setup; end
  def before_teardown; end
  def teardown; end
  def after_teardown; end
end
```
