### ISSUE TITLE
New cop: `Minitest/AssertSame`

### ISSUE THREAD

**Issue by fatkodima** [rubocop/rubocop-minitest#215]
https://docs.ruby-lang.org/en/2.1.0/MiniTest/Assertions.html#method-i-assert_same

```ruby
# bad
assert foo.equal?(bar)
refute foo.equal?(bar)

# good
assert_same foo, bar
refute_same foo, bar
```

In the `rails/rails` codebase by a quick regexp search I found 30+ offenses of this.

**Comment by koic** [comment]
Good catch! This will open a PR in the style guide first.

**Comment by andyw8** [comment]
I have a slight concern here: `same` is less explicit than `equal?`. It's not obvious what kind of comparison is being (`==`, etc. ) made unless you look at the implementation or docs.
