### ISSUE TITLE
New cop: `Minitest/PrivateTestMethod`

### ISSUE THREAD

**Issue by fatkodima** [rubocop/rubocop-minitest#220]
While adding a new test case to a large codebase (`rails/rails` as an example) with its test files sometimes having thousands of lines of code and not following TDD (as I believe most of people do, mine included, except for bugfixes), it is very easy to add a test case to the `private` class section. The test case won't be run and the developer will think that tests are passing.

```ruby
# bad
class FooTest < Minitest::Test
  def test_foo; end

  private
  def test_bar
  end
end

# good
class FooTest < Minitest::Test
  def test_foo; end
  def test_bar; end
end

# good
class FooTest < Minitest::Test
  def test_foo; end

  private
  def bar
  end
end
```

**Comment by koic** [comment]
I agree that this is probably out of the xUnit execution pattern. However, I'm not sure if that was intentional or a mistake by user. First of all, it may be better to specify it in Minitest Style Guide as it will become a stronger basis as a rule:
https://github.com/rubocop/minitest-style-guide

**Comment by andyw8** [comment]
I'd say that if the test name begins `test_` then it's reasonable to assume it was a mistake to make it private.

**Comment by fatkodima** [comment]
I think, we could also check for assertions inside that method. In this case it is 100% a mistake.

**Comment by koic** [comment]
Okay, It doesn't have to be checked inside the method. Note, `protected` should also be treated the same as `private`. So, the cop name can be adjusted if we gets good inspiration.
