### ISSUE TITLE
New cop to detect `return`s in test cases

### ISSUE THREAD

**Issue by fatkodima** [rubocop/rubocop-minitest#236]
```ruby
# bad
def test_check_constraints
  return if mysql?
  # do testing
end

# good
def test_check_constraints
  skip("MySQL does not support check constraints") if mysql?
  # do testing
end
```
Example: https://github.com/gregnavis/active_record_doctor/blob/fc736812db046e2c0bfdbb6cec0b837e01a35076/test/active_record_doctor/detectors/mismatched_foreign_key_type_test.rb#L6

When using `skip`, minitest will report a skipped tests summary at the end; `--verbose` and `--show-skips` will show skips (https://github.com/minitest/minitest/blob/0984e29995a5c0f4dcf3c185442bcb4f493ed5e3/lib/minitest.rb#L208-L214); [minitest-reporters](https://github.com/minitest-reporters/minitest-reporters) will show the skipped tests; `skip` requires a reason with the existing cop (`SkipWithoutReason`) and overall it is more clear the intention, than just simple `return`.

**Comment by koic** [comment]
This seems good idea. Can you open to the Minitest Style Guide first?

**Comment by fatkodima** [comment]
@tejasbubane Thank you for the PR into the style guide! Do you want to implement this check too?

**Comment by tejasbubane** [comment]
@fatkodima Yes I'll work on the implementation within a day or two.
