### ISSUE TITLE
New version needed: Rubocop-Minitest assert_offense breaks on rubocop 1.48.0

### ISSUE THREAD

**Issue by broksonic21** [rubocop/rubocop-minitest#243]
--------

## Expected behavior

Latest rubocop-minitest should work with rubocop 1.48.0 (latest rubocop)

## Actual behavior

assert_offense fails as it doesn't pass a configuration in.

See https://github.com/rubocop/rubocop/issues/11670

## Steps to reproduce the problem

Use assert_offense using rubocop 1.48.0, but a commit of rubocop-minitest prior to https://github.com/rubocop/rubocop-minitest/commit/fcf0a8f33739f88b8ac4aaca0e4d47977e2fc76d (which isn't released yet)

## RuboCop version

```
1.48.0 (using Parser 3.2.1.0, rubocop-ast 1.27.0, running on ruby 2.7.7) [arm64-darwin21]
  - rubocop-minitest 0.28.0
```

**Comment by koic** [comment]
RuboCop Minitest 0.29 has been released:
https://github.com/rubocop/rubocop-minitest/releases/tag/v0.29.0

Please upgrade to the latest version. Thank you.

**Comment by broksonic21** [comment]
Thanks @koic , confirming that fixed the issue for us!
