### ISSUE TITLE
Extend `AssertEmpty` to detect `assert_equal 0, collection.size`

### ISSUE THREAD

**Issue by fatkodima** [rubocop/rubocop-minitest#245]
```ruby
# bad
assert_equal 0, collection.size # or .length or .count

# good
assert_empty collection
```

Recent examples from the wild - https://github.com/rails/rails/blob/3025eaa09154f5f031f5c2e0e5b59553ff5c902b/activerecord/test/cases/migration/unique_key_test.rb#L151-L156

This transformation can be unsafe, because it is possible to have a `.size`/`.count`/`.length` method, but to not have an `.empty?` method. By I do not think this case will be very popular.

**Comment by koic** [comment]
> Recent examples from the wild - https://github.com/rails/rails/blob/3025eaa09154f5f031f5c2e0e5b59553ff5c902b/activerecord/test/cases/migration/unique_key_test.rb#L151-L156

```ruby
          assert_equal 0, @connection.unique_keys("sections").size

          @connection.add_unique_key :sections, [:position], name: "unique_section_position"
          assert_equal 1, @connection.unique_keys("sections").size
          @connection.remove_unique_key :sections, name: "unique_section_position"
          assert_equal 0, @connection.unique_keys("sections").size
```

Hm, I'm wondering if it makes sense to always force it, because I think there are benefits to being able to consist and align with `assert_equal n, @connection.unique_keys("sections").size`.

> This transformation can be unsafe, because it is possible to have a `.size`/`.count`/`.length` method, but to not have an `.empty?` method.

Yeah, there's maybe no advantage to trading safe detection of currently.
