### ISSUE TITLE
Enforce assert_operator instead of assert with operator expression

### ISSUE THREAD

**Issue by TSMMark** [rubocop/rubocop-minitest#255]
## Is your feature request related to a problem? Please describe.

When reviewing PRs of teammates using for example `assert(a < b)`

## Describe the solution you'd like

I'd like rubocop to recommend for example `assert_operator(a, :<, b)`

## Additional context

I was surprised I couldn't find this cop, as it seems pretty simple to implement (possibly naively) and it's in the minitest style guide https://github.com/rubocop/minitest-style-guide#assert-operator

Would you accept a PR for a new cop `Minitest/AssertOperator` ?

Thanks

**Comment by andyw8** [comment]
👍 Sounds like a useful cop to add.
