### ISSUE TITLE
refute_equal tests and refute_equal matcher are both wrong

### ISSUE THREAD

**Issue by zenspider** [rubocop/rubocop-minitest#256]
```ruby
assert(!'rubocop-minitest' == actual)
```

is "(not string) equals actual", not "not (string equals actual)" as seen with ruby-parse:

```
3858 % rake parse R='assert(!A == B)'
(send nil :assert
  (send
    (send
      (const nil :A) :!) :==
    (const nil :B)))
```
instead, you want:

```
3859 % rake parse R='assert(!(A == B))'
(send nil :assert
  (send
    (begin
      (send
        (const nil :A) :==
        (const nil :B))) :!))
```

the matcher follows suit:

```ruby
        def_node_matcher :assert_not_equal, <<~PATTERN
          (send nil? :assert {(send $_ :!= $_) (send (send $_ :! ) :== $_) } $... )
        PATTERN
```

**Comment by andyw8** [comment]
FYI @duduribeiro who contributed this in https://github.com/rubocop/rubocop-minitest/pull/21

**Comment by zenspider** [comment]
cc @koic for https://github.com/rubocop/rubocop-minitest/pull/21#discussion_r331714787

**Comment by koic** [comment]
FYI, RuboCop Minitest 0.31.1 has been released.
https://github.com/rubocop/rubocop-minitest/releases/tag/v0.31.1
