### ISSUE TITLE
Minitest/TestMethodName false negative

### ISSUE THREAD

**Issue by MatzFan** [rubocop/rubocop-minitest#312]
No offense is registered with the following setup:

`foo.rb`
```ruby
# frozen_string_literal: true

# class
class Foo
  def bar
    'Hello world'
  end
end

```
`test_foo.rb`
```ruby
# frozen_string_literal: true

require 'minitest/autorun'
require_relative 'foo'

# tests
class TestFoo < Minitest::Test
  def test_bar
    assert_raises(ArgumentError) { Foo.new.bar('an_arg') }
  end

  def not_a_test
    assert_raises(ArgumentError) { Foo.new.bar('an_arg') }
  end
end

```
`.rubocop.yml`
```yaml
require: rubocop-minitest

AllCops:
  NewCops: enable

Minitest/TestMethodName:
  Enabled: true

```
--------

## Expected behavior

I expect an offense for the second method in the test file.

## Actual behavior

No offense is registered.

## Steps to reproduce the problem

Run `rubocop` or `rubocop --require rubocop-minitest` in the root directory with the above files.

## RuboCop version
```
1.65.0 (using Parser 3.3.4.0, rubocop-ast 1.31.3, running on ruby 3.3.4) [x86_64-linux]
  - rubocop-minitest 0.35.1
```

**Comment by andyw8** [comment]
Your test class name should end in `Test`:

https://github.com/rubocop/rubocop-minitest/blob/4d08365be08d06b02bb2c11415a4e8060331a0bb/lib/rubocop/cop/mixin/minitest_exploration_helpers.rb#L29

**Comment by MatzFan** [comment]
Thanks. Same result with
```ruby
class FooTest < Minitest::Test
  def test_bar
    assert_raises(ArgumentError) { Foo.new.bar('an_arg') }
  end

  def not_a_test
    assert_raises(ArgumentError) { Foo.new.bar('an_arg') }
  end
end
```
And if my test classes are not correctly named shouldn't that trigger another cop? TestFoo [seems to be](https://github.com/minitest/minitest?tab=readme-ov-file#unit-tests-) the correct convention for Minitest class names and is the one I've always used.

**Comment by MatzFan** [comment]
OK, so after a class rename the problem is solved in my project. Agree 'Test' suffix is better anyhow. Thanks for your help.
